-- Backfill codigo_cliente pros registros já importados de Set/2026 e Out/2026
-- (coluna 'Código do cliente' existia na planilha original mas não tinha campo
-- correspondente no banco antes da migration 0149 -- ver lojas_maia_pendencias).
-- 210 casados por (origem_planilha, nf) -- NF único entre as linhas já importadas.
-- 18 casados por (origem_planilha, nf, cliente) -- NF '-' repetido
-- (sem NF de verdade na planilha), cliente confirmado único dentro desse grupo.
-- Guard codigo_cliente is null evita sobrescrever algo preenchido manualmente depois.

update assistencia_cadastros_historico set codigo_cliente = '116688' where origem_planilha = 'Set/2026' and nf = '20746' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '100322' where origem_planilha = 'Set/2026' and nf = '25791' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '113484' where origem_planilha = 'Set/2026' and nf = '51687' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118388' where origem_planilha = 'Set/2026' and nf = '19600' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117510' where origem_planilha = 'Set/2026' and nf = '4423' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '71964' where origem_planilha = 'Set/2026' and nf = '20544' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '106468' where origem_planilha = 'Set/2026' and nf = '52305' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116100' where origem_planilha = 'Set/2026' and nf = '26028' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '96754' where origem_planilha = 'Set/2026' and nf = '46233' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118448' where origem_planilha = 'Set/2026' and nf = '4554' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '85717' where origem_planilha = 'Set/2026' and nf = '16935' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '75666' where origem_planilha = 'Set/2026' and nf = '28813' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '55319' where origem_planilha = 'Set/2026' and nf = '29283' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '107369' where origem_planilha = 'Set/2026' and nf = '2643' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '113373' where origem_planilha = 'Set/2026' and nf = '19103' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '81943' where origem_planilha = 'Set/2026' and nf = '49942' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117791' where origem_planilha = 'Set/2026' and nf = '21619' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115425' where origem_planilha = 'Set/2026' and nf = '25206' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '100525' where origem_planilha = 'Set/2026' and nf = '19868' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117743' where origem_planilha = 'Set/2026' and nf = '25753' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116734' where origem_planilha = 'Set/2026' and nf = '25813' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118029' where origem_planilha = 'Set/2026' and nf = '12474' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118483' where origem_planilha = 'Set/2026' and nf = '16776' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119097' where origem_planilha = 'Set/2026' and nf = '52790' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116104' where origem_planilha = 'Set/2026' and nf = '26636' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119517' where origem_planilha = 'Set/2026' and nf = '52950' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117507' where origem_planilha = 'Set/2026' and nf = '24859' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116722' where origem_planilha = 'Set/2026' and nf = '52141' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118160' where origem_planilha = 'Set/2026' and nf = '19617' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117332' where origem_planilha = 'Set/2026' and nf = '5361' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117361' where origem_planilha = 'Set/2026' and nf = '52289' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '85409' where origem_planilha = 'Set/2026' and nf = '21601' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '94293' where origem_planilha = 'Set/2026' and nf = '17674' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119258' where origem_planilha = 'Set/2026' and nf = '52890' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118972' where origem_planilha = 'Set/2026' and nf = '16805' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '75834' where origem_planilha = 'Set/2026' and nf = '12345' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116628' where origem_planilha = 'Set/2026' and nf = '19481' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '60491' where origem_planilha = 'Set/2026' and nf = '52851' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '112743' where origem_planilha = 'Set/2026' and nf = '24914' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '41265' where origem_planilha = 'Set/2026' and nf = '53057' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '97614' where origem_planilha = 'Set/2026' and nf = '49294' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117758' where origem_planilha = 'Set/2026' and nf = '291' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119715' where origem_planilha = 'Set/2026' and nf = '53060' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '106588' where origem_planilha = 'Set/2026' and nf = '25015' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118410' where origem_planilha = 'Set/2026' and nf = '53052' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118983' where origem_planilha = 'Set/2026' and nf = '16787' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119955' where origem_planilha = 'Set/2026' and nf = '22994' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '108324' where origem_planilha = 'Set/2026' and nf = '23077' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '56357' where origem_planilha = 'Set/2026' and nf = '26599' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '85418' where origem_planilha = 'Set/2026' and nf = '52636' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '34484' where origem_planilha = 'Set/2026' and nf = '52929' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '63794' where origem_planilha = 'Set/2026' and nf = '25635' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '92135' where origem_planilha = 'Set/2026' and nf = '17220' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120160' where origem_planilha = 'Set/2026' and nf = '53167' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = 'VF0529' where origem_planilha = 'Set/2026' and nf = '51451' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117651' where origem_planilha = 'Set/2026' and nf = '52464' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119955' where origem_planilha = 'Set/2026' and nf = '26957' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117379' where origem_planilha = 'Set/2026' and nf = '24857' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119177' where origem_planilha = 'Set/2026' and nf = '23175' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '112291' where origem_planilha = 'Set/2026' and nf = '23813' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '110875' where origem_planilha = 'Set/2026' and nf = '24347' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117696' where origem_planilha = 'Set/2026' and nf = '22937' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116378' where origem_planilha = 'Set/2026' and nf = '21052' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119529' where origem_planilha = 'Set/2026' and nf = '52952' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115285' where origem_planilha = 'Set/2026' and nf = '51794' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118853' where origem_planilha = 'Set/2026' and nf = '4748' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '111999' where origem_planilha = 'Set/2026' and nf = '23071' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '27023' where origem_planilha = 'Set/2026' and nf = '48560' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118048' where origem_planilha = 'Set/2026' and nf = '21688' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117785' where origem_planilha = 'Set/2026' and nf = '20906' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119000' where origem_planilha = 'Set/2026' and nf = '26711' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119643' where origem_planilha = 'Set/2026' and nf = '23103' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119079' where origem_planilha = 'Set/2026' and nf = '52788' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119050' where origem_planilha = 'Set/2026' and nf = '53230' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '112436' where origem_planilha = 'Set/2026' and nf = '27128' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '70063' where origem_planilha = 'Set/2026' and nf = '12554' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '37114' where origem_planilha = 'Set/2026' and nf = '25776' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '39212' where origem_planilha = 'Set/2026' and nf = '53222' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116195' where origem_planilha = 'Set/2026' and nf = '21945' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115210' where origem_planilha = 'Set/2026' and nf = '23169' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117638' where origem_planilha = 'Set/2026' and nf = '19583' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120481' where origem_planilha = 'Set/2026' and nf = '53282' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115801' where origem_planilha = 'Set/2026' and nf = '25021' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '19293' where origem_planilha = 'Set/2026' and nf = '27391' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '96827' where origem_planilha = 'Set/2026' and nf = '53422' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120344' where origem_planilha = 'Set/2026' and nf = '27177' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120566' where origem_planilha = 'Set/2026' and nf = '27103' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119997' where origem_planilha = 'Set/2026' and nf = '25011' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119847' where origem_planilha = 'Set/2026' and nf = '53068' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '68163' where origem_planilha = 'Set/2026' and nf = '23375' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120467' where origem_planilha = 'Set/2026' and nf = '19786' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '113835' where origem_planilha = 'Set/2026' and nf = '51463' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '103074' where origem_planilha = 'Set/2026' and nf = '23747' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120736' where origem_planilha = 'Set/2026' and nf = '26225' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '114153' where origem_planilha = 'Set/2026' and nf = '53181' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115734' where origem_planilha = 'Set/2026' and nf = '25436' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '106507' where origem_planilha = 'Set/2026' and nf = '18418' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120703' where origem_planilha = 'Set/2026' and nf = '23320' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121375' where origem_planilha = 'Set/2026' and nf = '27389' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118452' where origem_planilha = 'Set/2026' and nf = '53219' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121469' where origem_planilha = 'Set/2026' and nf = '27399' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '113791' where origem_planilha = 'Set/2026' and nf = '10373' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121622' where origem_planilha = 'Set/2026' and nf = '5033' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120668' where origem_planilha = 'Set/2026' and nf = '4867' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120391' where origem_planilha = 'Set/2026' and nf = '4889' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117294' where origem_planilha = 'Set/2026' and nf = '4309' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118314' where origem_planilha = 'Set/2026' and nf = '4871' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119403' where origem_planilha = 'Set/2026' and nf = '4709' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '102917' where origem_planilha = 'Set/2026' and nf = '933' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '108248' where origem_planilha = 'Set/2026' and nf = '25052' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120206' where origem_planilha = 'Set/2026' and nf = '22021' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117521' where origem_planilha = 'Set/2026' and nf = '533357' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119637' where origem_planilha = 'Set/2026' and nf = '21881' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118966' where origem_planilha = 'Set/2026' and nf = '26635' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121292' where origem_planilha = 'Set/2026' and nf = '12624' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '113006' where origem_planilha = 'Set/2026' and nf = '22011' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120952' where origem_planilha = 'Set/2026' and nf = '53511' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120686' where origem_planilha = 'Set/2026' and nf = '25138' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '54912' where origem_planilha = 'Set/2026' and nf = '14851' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119882' where origem_planilha = 'Set/2026' and nf = '12689' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121669' where origem_planilha = 'Set/2026' and nf = '53769' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '48831' where origem_planilha = 'Set/2026' and nf = '53675' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122556' where origem_planilha = 'Set/2026' and nf = '22421' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122442' where origem_planilha = 'Set/2026' and nf = '19938' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121164' where origem_planilha = 'Set/2026' and nf = '22243' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119913' where origem_planilha = 'Set/2026' and nf = '53376' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '109722' where origem_planilha = 'Set/2026' and nf = '21521' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116361' where origem_planilha = 'Set/2026' and nf = '23148' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '45642' where origem_planilha = 'Set/2026' and nf = '49379' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '110579' where origem_planilha = 'Set/2026' and nf = '51880' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122130' where origem_planilha = 'Set/2026' and nf = '10420' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118576' where origem_planilha = 'Set/2026' and nf = '53244' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115699' where origem_planilha = 'Set/2026' and nf = '5119' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120679' where origem_planilha = 'Set/2026' and nf = '21250' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122249' where origem_planilha = 'Set/2026' and nf = '28072' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '110786' where origem_planilha = 'Set/2026' and nf = '18904' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121752' where origem_planilha = 'Set/2026' and nf = '12634' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122040' where origem_planilha = 'Set/2026' and nf = '10381' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121642' where origem_planilha = 'Set/2026' and nf = '22235' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '91493' where origem_planilha = 'Set/2026' and nf = '27019' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '22962' where origem_planilha = 'Set/2026' and nf = '25172' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '111788' where origem_planilha = 'Set/2026' and nf = '24548' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122188' where origem_planilha = 'Set/2026' and nf = '21450' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '81382' where origem_planilha = 'Set/2026' and nf = '51559' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122151' where origem_planilha = 'Set/2026' and nf = '19939' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '45799' where origem_planilha = 'Set/2026' and nf = '52903' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118039' where origem_planilha = 'Set/2026' and nf = '12569' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '45440' where origem_planilha = 'Set/2026' and nf = '53637' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121682' where origem_planilha = 'Set/2026' and nf = '27554' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121196' where origem_planilha = 'Set/2026' and nf = '19871' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '105080' where origem_planilha = 'Set/2026' and nf = '18171' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119069' where origem_planilha = 'Set/2026' and nf = '53584' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '96301' where origem_planilha = 'Set/2026' and nf = '18590' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '29960' where origem_planilha = 'Set/2026' and nf = '22493' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '98287' where origem_planilha = 'Set/2026' and nf = '22643' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120560' where origem_planilha = 'Set/2026' and nf = '23338' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123257' where origem_planilha = 'Set/2026' and nf = '26468' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115999' where origem_planilha = 'Set/2026' and nf = '22588' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121938' where origem_planilha = 'Set/2026' and nf = '19916' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '34484' where origem_planilha = 'Set/2026' and nf = '53047' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120292' where origem_planilha = 'Set/2026' and nf = '53961' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122370' where origem_planilha = 'Set/2026' and nf = '19982' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122345' where origem_planilha = 'Set/2026' and nf = '19967' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123012' where origem_planilha = 'Set/2026' and nf = '5373' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '45734' where origem_planilha = 'Set/2026' and nf = '26482' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117290' where origem_planilha = 'Set/2026' and nf = '20074' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122348' where origem_planilha = 'Set/2026' and nf = '10431' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121027' where origem_planilha = 'Set/2026' and nf = '27425' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '108820' where origem_planilha = 'Set/2026' and nf = '19324' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116533' where origem_planilha = 'Set/2026' and nf = '4166' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121462' where origem_planilha = 'Set/2026' and nf = '53682' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119495' where origem_planilha = 'Set/2026' and nf = '4845' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122505' where origem_planilha = 'Set/2026' and nf = '22488' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '87110' where origem_planilha = 'Set/2026' and nf = '2246' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '86052' where origem_planilha = 'Set/2026' and nf = '41048' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123589' where origem_planilha = 'Set/2026' and nf = '28543' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116197' where origem_planilha = 'Set/2026' and nf = '5575' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117060' where origem_planilha = 'Set/2026' and nf = '4259' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121313' where origem_planilha = 'Set/2026' and nf = '7799' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121089' where origem_planilha = 'Set/2026' and nf = '25265' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122369' where origem_planilha = 'Set/2026' and nf = '19927' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '68027' where origem_planilha = 'Set/2026' and nf = '30078' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '45605' where origem_planilha = 'Set/2026' and nf = '25454' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120008' where origem_planilha = 'Set/2026' and nf = '25461' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '40796' where origem_planilha = 'Set/2026' and nf = '15653' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122066' where origem_planilha = 'Set/2026' and nf = '74' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '116378' where origem_planilha = 'Set/2026' and nf = '21153' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120586' where origem_planilha = 'Set/2026' and nf = '27179' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122343' where origem_planilha = 'Set/2026' and nf = '5300' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '72642' where origem_planilha = 'Set/2026' and nf = '30135' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '112293' where origem_planilha = 'Set/2026' and nf = '24352' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '90273' where origem_planilha = 'Set/2026' and nf = '54079' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121807' where origem_planilha = 'Set/2026' and nf = '5222' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123491' where origem_planilha = 'Set/2026' and nf = '54076' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119933' where origem_planilha = 'Set/2026' and nf = '28713' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119891' where origem_planilha = 'Set/2026' and nf = '54112' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '117971' where origem_planilha = 'Set/2026' and nf = '22907' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121411' where origem_planilha = 'Set/2026' and nf = '25239' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120292' where origem_planilha = 'Set/2026' and nf = '54113' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123670' where origem_planilha = 'Set/2026' and nf = '26550' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '92870' where origem_planilha = 'Set/2026' and nf = '26559' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '124072' where origem_planilha = 'Set/2026' and nf = '28703' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '98287' where origem_planilha = 'Set/2026' and nf = '23722' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123909' where origem_planilha = 'Set/2026' and nf = '23726' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '80951' where origem_planilha = 'Set/2026' and nf = '8323' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123727' where origem_planilha = 'Set/2026' and nf = '22756' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '115374' where origem_planilha = 'Set/2026' and nf = '12619' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120949' where origem_planilha = 'Set/2026' and nf = '27510' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119482' where origem_planilha = 'Set/2026' and nf = '19686' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '118542' where origem_planilha = 'Out/2026' and nf = '53401' and codigo_cliente is null;

update assistencia_cadastros_historico set codigo_cliente = '120483' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'RONALDO NUNES' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121268' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'ALEFF SANTOS FERREIRA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121604' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'NAIA ANTUNES DE REZENDE' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122952' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'JONATHAS DO CARMO RODRIGUES' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121977' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'MARLUCE DE ARAUJO' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '120219' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'MARIA JOSE MATIAS RAMOS IRMA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '75363' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'TAMILLYS ELAINE SOARES DA SILVA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '19979' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'THIAGO DOS SANTOS SOUSA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123019' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'SAYONAYARA QUEIROZ DO NASCIMENTO' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122815' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'RITA DE CASSIA DOS SANTOS CARDOSO' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122552' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'GEOVANA VITORIA SANTOS FERREIRA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '24388' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'JOSEFA FLAILMA DANTAS DOS SANTOS' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '122543' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'MILENA VANESSA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '119834' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'LIDIA MELO DE AMORIM' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123954' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'JANAINA DA CONCEICAO BARBOSA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '121601' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'MARIA ELIZABETHY COSTA VIANA' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '123800' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'MAISA DA SILVA GONÇALVES' and codigo_cliente is null;
update assistencia_cadastros_historico set codigo_cliente = '124339' where origem_planilha = 'Set/2026' and nf = '-' and cliente = 'LUAN JOSE SILVA DOS SANTOS' and codigo_cliente is null;
